### ISSUE TITLE
Could not load library client.so

### ISSUE THREAD

**Issue by Fujinn981** [tmp64/hl1_source_sdk#1]
I've tried for a very basic implementation of IClientVGUI, however upon calling vgui2::VGui_InitInterfacesList client.so will no longer load.

My (very basic, just wanted to test if it would work before making a proper one) implementation can be seen here:

```cpp

 #include <tier0/dbg.h>
 #include <tier1/interface.h>
 #include <tier1/tier1.h>
 #include <tier2/tier2.h>
 

 
namespace vgui2
{
bool VGui_InitInterfacesList(const char *moduleName, CreateInterfaceFn *factoryList, int numFactories);
}



 class CClientVGUI
 {
     
     virtual void Initialize(CreateInterfaceFn *pFactories, int numFactories);
     
};

 


 void CClientVGUI::Initialize(CreateInterfaceFn *pFactories, int iNumFactories)
 {
 	ConnectTier1Libraries(pFactories, iNumFactories);
 	ConnectTier2Libraries(pFactories, iNumFactories);


 	if (!vgui2::VGui_InitInterfacesList("CLIENT", pFactories, iNumFactories))
 	{
 		Error("Failed to intialize VGUI2\n");
 		Assert(false);
    }
 } 
```

Commenting out the if statement allows the client to load. I've followed the steps although I am relatively new to Cmake.

Upon compilation when trying to call vgui2::InitInterfacesList I get the following warning:

/usr/bin/ld: ../hl1_source_sdk/vgui2/vgui_controls/libvgui_controls.a(Panel.cpp.o): warning: relocation against `_ZNSt8_Rb_treeIiSt4pairIKiNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEESt10_Select1stIS8_ESt4lessIiESaIS8_EE6_S_keyEPKSt18_Rb_tree_node_base' in read-only section `.text._ZNSt8_Rb_treeIiSt4pairIKiNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEESt10_Select1stIS8_ESt4lessIiESaIS8_EE24_M_get_insert_unique_posERS1_[_ZNSt8_Rb_treeIiSt4pairIKiNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEESt10_Select1stIS8_ESt4lessIiESaIS8_EE24_M_get_insert_unique_posERS1_]'

Any attempt to call the aforementioned function will cause the client to not load.

I'm really hoping some one here will have a clue as to what's causing this as I've been wanting to add vgui elements to the mod I'm working on. Any help is highly appreciated. :)

**Comment by tmp64** [comment]
This warning is caused by position-independent not being enabled and shouldn't cause any run-time issues. See https://github.com/YaLTeR/OpenAG/pull/83 on details how to fix it.

The problem is most likely caused by a change I made a while ago and didn't update the README.md: you need to implement `vgui2::VGui_GetDefaultScheme`. See this commit for details: https://github.com/tmp64/BugfixedHL-Rebased/commit/477beef65cb56a9e463e925adf8d1e21ad28eca9

There also a few other incompatibilities not reflected in the README.md:
- Source SDK's `Color` conflicts with `vgui::Color` from VGUI1. It can be solved by changing all `Color` references in VGUI1 code (headers and client panels) to `vgui::Color` or by removing it entirely.
- Source SDK's mathlib conflicts with HLSDKs Vector classes so HLSDK needs some refactoring: https://github.com/tmp64/BugfixedHL-Rebased/commit/108ce31d860730843835d3159c1b582df7e9f635
- VGUI1 and VGUI2 headers include guards use `VGUI_PANEL_NAME_H` define. This prevents including both VGUI1 and VGUI2 headers in one .cpp file. I replaced them with `VGUI1_PANEL_NAME_H` here: https://github.com/tmp64/BugfixedHL-Rebased/tree/108ce31d860730843835d3159c1b582df7e9f635/external/vgui/include

On final note, I suggest you use VGUI2 viewport sources and controls from https://github.com/tmp64/BugfixedHL-Rebased/tree/master/src/game/client (client_vgui.h/.cpp, directories vgui and gameui) instead of implementing custom ones.

**Comment by Fujinn981** [comment]
> This warning is caused by position-independent not being enabled and shouldn't cause any run-time issues. See [YaLTeR/OpenAG#83](https://github.com/YaLTeR/OpenAG/pull/83) on details how to fix it.
> 
> The problem is most likely caused by a change I made a while ago and didn't update the README.md: you need to implement `vgui2::VGui_GetDefaultScheme`. See this commit for details: [tmp64/BugfixedHL-Rebased@477beef](https://github.com/tmp64/BugfixedHL-Rebased/commit/477beef65cb56a9e463e925adf8d1e21ad28eca9)
> 
> There also a few other incompatibilities not reflected in the README.md:
> 
>     * Source SDK's `Color` conflicts with `vgui::Color` from VGUI1. It can be solved by changing all `Color` references in VGUI1 code (headers and client panels) to `vgui::Color` or by removing it entirely.
> 
>     * Source SDK's mathlib conflicts with HLSDKs Vector classes so HLSDK needs some refactoring: [tmp64/BugfixedHL-Rebased@108ce31](https://github.com/tmp64/BugfixedHL-Rebased/commit/108ce31d860730843835d3159c1b582df7e9f635)
> 
>     * VGUI1 and VGUI2 headers include guards use `VGUI_PANEL_NAME_H` define. This prevents including both VGUI1 and VGUI2 headers in one .cpp file. I replaced them with `VGUI1_PANEL_NAME_H` here: https://github.com/tmp64/BugfixedHL-Rebased/tree/108ce31d860730843835d3159c1b582df7e9f635/external/vgui/include
> 
> 
> On final note, I suggest you use VGUI2 viewport sources and controls from https://github.com/tmp64/BugfixedHL-Rebased/tree/master/src/game/client (client_vgui.h/.cpp, directories vgui and gameui) instead of implementing custom ones.


That did the trick! Thank you very much for the help and all of the information. :) This will go a long way in helping with the development of the mod.
